# Generated by Django 2.2.6 on 2024-04-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('object_status', models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0)),
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(max_length=50)),
                ('alphaTwoCode', models.CharField(max_length=50)),
                ('countryId', models.CharField(max_length=70)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
