# Generated by Django 2.2.6 on 2024-04-03 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0002_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sportapp.Country'),
        ),
    ]
