# Generated by Django 2.2.6 on 2024-04-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0003_auto_20240403_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page_Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('meta_title', models.TextField(null=True)),
                ('meta_description', models.TextField(null=True)),
                ('meta_keyword', models.TextField(null=True)),
                ('og_img', models.ImageField(upload_to='uploads/og_img')),
                ('img_alt', models.CharField(max_length=100, null=True)),
                ('canonical_url', models.URLField(null=True)),
                ('datetime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
