# Generated by Django 2.2.6 on 2024-04-03 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('short_desc', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(default='')),
                ('img', models.ImageField(upload_to='uploads/og_img')),
                ('image_caption', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Published'), (2, 'Rejected')])),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(default='')),
                ('img', models.ImageField(upload_to='uploads/og_img')),
                ('image_caption', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(default='')),
                ('img', models.ImageField(upload_to='uploads/og_img')),
                ('image_caption', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateField(auto_now_add=True)),
                ('blog_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.BlogCategory')),
            ],
        ),
        migrations.CreateModel(
            name='BlogSubCategory_Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('meta_title', models.TextField(null=True)),
                ('meta_description', models.TextField(null=True)),
                ('meta_keyword', models.TextField(null=True)),
                ('og_img', models.ImageField(upload_to='uploads/og_img')),
                ('image_caption', models.CharField(max_length=100, null=True)),
                ('canonical_url', models.URLField(null=True)),
                ('datetime', models.DateField(auto_now_add=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.BlogSubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory_Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('meta_title', models.TextField(null=True)),
                ('meta_description', models.TextField(null=True)),
                ('meta_keyword', models.TextField(null=True)),
                ('og_img', models.ImageField(upload_to='uploads/og_img')),
                ('image_caption', models.CharField(max_length=100, null=True)),
                ('canonical_url', models.URLField(null=True)),
                ('datetime', models.DateField(auto_now_add=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.BlogCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('meta_title', models.TextField(null=True)),
                ('meta_description', models.TextField(null=True)),
                ('meta_keyword', models.TextField(null=True)),
                ('og_img', models.ImageField(upload_to='uploads/og_img')),
                ('image_caption', models.CharField(max_length=100, null=True)),
                ('canonical_url', models.URLField(null=True)),
                ('datetime', models.DateField(auto_now_add=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Blog')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.BlogCategory'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.BlogSubCategory'),
        ),
    ]
