# Generated by Django 2.2.6 on 2024-04-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20240403_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_desc',
            field=models.TextField(null=True),
        ),
    ]
